services:
  - type: web
    name: proyecto-abcc
    runtime: php
    buildCommand: |
      chmod -R 755 storage bootstrap/cache
      composer install --optimize-autoloader --no-dev
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=${PORT:-8000}
