services:
  - type: web
    name: ProyectoABCC_LARAVEL
    env: docker
    dockerfilePath: ./Dockerfile  # Render detectará y usará automáticamente este Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: rO8k2KG5VpoxcdXaBSrepPM8l8ISOgLQQXsUAxhPZGA=  # sin "<>" ni comentario
